### ISSUE TITLE
node 6.16.0 problems with toLocaleString

### ISSUE THREAD

**Issue by AndriyHromyak** [Homebrew/formulae.brew.sh#100]
can i have ability to install node version 6.12.*? latest node 6.16.0 behaves strange, seems it doesn't have Intl inside, its just empty object, and my Jest tests fails because of this. can anyone suggest solution or workaround?

main problem is that (3500).toLocaleString() does nothing, it returns 3500 instead of 3,500

**Comment by MikeMcQuaid** [comment]
You will need to create your own tap.

**Comment by AndriyHromyak** [comment]
Can you point me where i can read about creating taps? i have solved that issue by switching to nvm however i would like to know how to solve it via brew.

**Comment by MikeMcQuaid** [comment]
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
