### ISSUE TITLE
Formulae from deprecated taps shouldn’t be listed by default

### ISSUE THREAD

**Issue by koraktor** [Homebrew/formulae.brew.sh#100]
We could take a similar approach to deleted formulae which can still be accessed by URL, but not by browsing / searching.

See #95

**Comment by MikeMcQuaid** [comment]
👍

**Comment by sjackman** [comment]
Thanks, Sebastian.

**Comment by qaisjp** [comment]
I'm looking into this — is there a way to programmatically find out whether a tap is deprecated?

**Comment by sjackman** [comment]
Yes. See https://developer.github.com/changes/2017-11-08-archiving-repositories/
```
❯❯❯ curl -s https://api.github.com/repos/homebrew/homebrew-science | jq .archived
true
```

**Comment by qaisjp** [comment]
Ah great, so we just use repository archival as an indicator.

**Comment by koraktor** [comment]
We already have `Repository#outdated?`.

See also https://github.com/Homebrew/formulae.brew.sh/blob/027b03be00bcdcbdb808e3974bd195f6e5e7259a/lib/main_import.rb#L45.

**Comment by koraktor** [comment]
Taps (and their data) are now gone. So this is not an issue any longer.

**Comment by sjackman** [comment]
Thanks, Sebastian.

I'd like to set a up a formula browser for the Brewsci/bio tap. Is there a Getting Started guide for getting this up and running on an ideally free-or-close-to-free hosting service?
