### ISSUE TITLE
Compilation advice

### ISSUE THREAD

**Issue by qaisjp** [Homebrew/formulae.brew.sh#102]
Is it worth me sending a PR to get the following info included in the README?

------

Things to do before following "Local setup":

- Update Ruby to the latest version
- Update bundler to the latest version
- Update everything(?) to the latest version (`gem pristine --all`)
- Then run the commands

**Comment by MikeMcQuaid** [comment]
@qaisjp None of that should be necessary; `script/bootstrap` will do it for you.

**Comment by qaisjp** [comment]
Unfortunately `./script/bootstrap` yielded errors for me (and/or `rake db:seed` did).

For context, I haven't done any Ruby development on this machine before (meaning I have the default Ruby installation and

I've lost my terminal scroll back but here are some of the things I googled to get `./script/bootstrap` to work:

- [`activate_bin_path error`](https://stackoverflow.com/questions/37805525/rails-2-2-2-issue-undefined-method-activate-bin-path-for-gemmodule-nomethod)
- [`rake incompatible library version`](https://stackoverflow.com/questions/34536351/how-do-i-resolve-incompatible-library-version-for-mysql2-gem-with-ruby-2-3-on)
- I also had to install RVM and a new version of ruby

**Comment by MikeMcQuaid** [comment]
> Unfortunately ./script/bootstrap yielded errors for me (and/or rake db:seed did).

Can you detail what those errors were? We can't fix them without knowing.
