### ISSUE TITLE
Where is the linuxbrew toggle?

### ISSUE THREAD

**Issue by JuPlutonic** [Homebrew/formulae.brew.sh#108]
Need it to see bottle info from linuxbrew.bintray.com instead of homebrew.bintray.com #45 .
And formulae from Homebrew/linuxbrew-core  instead of Homebrew/homebrew-core .

**Comment by MikeMcQuaid** [comment]
There isn't one. We'll accept PRs that add the necessary functionality but have no plans to do so.

**Comment by JuPlutonic** [comment]
Ok
