### ISSUE TITLE
Add Casks

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/formulae.brew.sh#13]
We should consider including Homebrew Casks into formulae.brew.sh. This would require generating an equivalent of `brew info --json=v1` for Casks on a Linux machine.

(Imported from https://github.com/Homebrew/formulae.brew.sh/issues/117 CC @adidalal)

**Comment by MikeMcQuaid** [comment]
> brew cask info {{cask_name}} does give you all the necessary details about a cask, and there's also brew cask _stanza {{stanza_name}} {{cask_name}} for specific bits.

Do either of them output JSON? If not, coming up with a format and building that on the Cask side would be a prerequisite.

**Comment by adidalal** [comment]
From my limited knowledge, I don't believe so.
/cc @reitermarkus @vitorgalvao for visibility

**Comment by reitermarkus** [comment]
`brew cask _stanza` has a `--yaml` option.

**Comment by MikeMcQuaid** [comment]
The Homebrew/brew side has been implemented in https://github.com/Homebrew/brew/pull/4410

**Comment by PatMyron** [comment]
From these:
https://github.com/Homebrew/brew.sh/pull/228
https://github.com/Homebrew/brew/pull/4620

It looks like @brianmorton is currently working on this, right?

Do you want any additional help? I'd love to see Cask analytics on the website

**Comment by MikeMcQuaid** [comment]
@PatMyron We've not seen any PRs and I've not had any additional communication there so I'd suggest you start your own work on this.

**Comment by brianmorton** [comment]
@PatMyron I am indeed mired in some stuff and help is always welcome :)

**Comment by PatMyron** [comment]
@luzpaz actually just switched jobs and moved myself, so I probably won't be making much progress on this anytime soon

**Comment by cmbernard333** [comment]
I would love to see this implemented. How can I get started to help contribute to this?

**Comment by brianmorton** [comment]
I am actually picking this back up this week (today).

**Comment by MikeMcQuaid** [comment]
I'd encourage others (e.g. @cmbernard333) to start their own implementations of this; I don't think it's worth blocking on a single individual.

**Comment by brianmorton** [comment]
@MikeMcQuaid I couldn't agree more!

I have actually just been trying to read back through all the previous threads and PRs to see what needs to be done. I think it might be helpful to put that information down here as it's a bit unclear.

The goal (as I currently understand it) is to update https://formulae.brew.sh/analytics/ to include cask analytics. That will necessitate updating various files in this repository.

Have I missed anything?

**Comment by cmbernard333** [comment]
Yeah if we can find a way to aggregate that stuff it would certainly make the implementation easier. I'm bit newer to brew so I'm still trying to find my way around.

**Comment by brianmorton** [comment]
@MikeMcQuaid we may have different goals - which is OK, there is some overlap. Originally I started contributing to brew (instead of just cask) so that I could increase the level of automation arounds casks... this required analytics of which casks were popular so we could focus our efforts.

Since then I have obviously stepped back a bit but I did want to finish what I had started here with the cask analytics, however I don't really want that to scope creep into much else as I'm not even sure how much of my original goal (cask automation) I will still be pursuing.

To that end, the work I am likely to open a PR for would be simply to make cask install analytics public... if others want to build on that I will leave that to them.

**Comment by MikeMcQuaid** [comment]
> To that end, the work I am likely to open a PR for would be simply to make cask install analytics public... if others want to build on that I will leave that to them.

Fine with me 👍

**Comment by cmbernard333** [comment]
@brianmorton would this work overlap with creating an API similar to what is provided via [https://formulae.brew.sh/docs/api/](formulae.json) or would additional work be required?

**Comment by brianmorton** [comment]
@cmbernard333 yes, as any automation of casks effort would require this.

**Comment by brianmorton** [comment]
OK so now that I've dug into this a bit more, it would be helpful if @MikeMcQuaid could confirm I am on the right path:

• update https://github.com/Homebrew/homebrew-formula-analytics with a command to be able to pull the cask analytics (which I previously implemented here: https://github.com/Homebrew/brew/pull/4620 )
• update this repo (formulae.brew.sh) with some layouts and an API to display the output of the new command which should generate a few JSON files for 30d, 90d, 365d

So this will require two PRs - one in each repo I believe.

Am I missing anything?

**Comment by brianmorton** [comment]
PRs created.

**Comment by cmbernard333** [comment]
What are the next steps needed to get an endpoint similar to https://formulae.brew.sh/docs/api/? Browsing the cask recipes from JSON would be super convenient.

**Comment by MikeMcQuaid** [comment]
@cmbernard333 Check out 
https://github.com/Homebrew/formulae.brew.sh/blob/master/script/generate.rb and https://github.com/Homebrew/formulae.brew.sh/blob/99e70e3ee9f5bb1c91683b587c25d3a954b68e01/Rakefile#L11 which would need casks added and 
https://github.com/Homebrew/homebrew-core/blob/master/.travis.yml#L35 which would need an equivalent for homebrew-cask.

**Comment by cmbernard333** [comment]
Awesome. I will do just that.

**Comment by cmbernard333** [comment]
@MikeMcQuaid Do you forsee this being added to `generate.rb` or as a separate `generate-cask.rb`? I only ask because the default `brew ruby` environment does not include or require `cask/cask`. 

There is also a current html template called _formula.html.in that matches the current `generate.rb`. _If_ we are generate a separate script for casks we might as well also use a separate template for casks.

**Comment by MikeMcQuaid** [comment]
@cmbernard333 You can do requires inside the `brew ruby` environment. One script would be ideal. I think it's probably worth focusing on generating just the JSON files and API first and then the HTML layout etc. in a follow-up.

**Comment by cmbernard333** [comment]
@MikeMcQuaid there are multiple casks that have the same internal `name` field as one another. Examples being `marmaduke-chromium` and `chromium`. Given these names are only provided via the filename of the recipe and not included in the recipe itself - how best should these be tackled?

**Comment by MikeMcQuaid** [comment]
@cmbernard333 I guess add a new `filename` field or similar and make that the "key" rather than the name.

**Comment by cmbernard333** [comment]
That makes sense. That is what is returned via the `brew search` command 

```
christianbernard@Dirac-MBP formulae.brew.sh (master) $ brew search --casks chromium
==> Casks
chromium                                          eloston-chromium                                  freesmug-chromium                                 marmaduke-chromium ✔                              marmaduke-chromium-nosync
```

**Comment by MikeMcQuaid** [comment]
Cask analytics data is now live: https://formulae.brew.sh/analytics/

**Comment by brianmorton** [comment]
Thanks to everyone that helped make this happen, and apologies it took so long.

**Comment by EricFromCanada** [comment]
`brew info` can now retrieve `cask-install` data: Homebrew/brew#5877

**Comment by brianmorton** [comment]
@EricFromCanada care to share a usage example?
i tried `brew info docker` and `brew info --analytics docker` (as well as `brew info --analytics --category=cask-install docker` but i'm not getting any cask install analytics.

```
$ brew info --analytics  docker
==> Analytics
==> install (30 days)
Index | Name (with options)                        |  Count |  Percent
-----:|--------------------------------------------|-------:|--------:
1     | docker                                     | 37,527 |   99.99%
2     | Docker                                     |      2 |    0.01%
Total |                                            | 37,529 |  100.00%
==> install (90 days)
Index | Name (with options)                        |  Count |  Percent
-----:|--------------------------------------------|-------:|--------:
1     | docker                                     | 96,594 |   99.99%
2     | Docker                                     |      3 |    0.00%
3     | docker --with-experimental                 |      3 |    0.00%
Total |                                            | 96,600 |  100.00%
==> install (365 days)
Index | Name (with options)                       |   Count |  Percent
-----:|-------------------------------------------|--------:|--------:
1     | docker                                    | 369,850 |   99.90%
2     | docker --with-experimental                |     346 |    0.09%
3     | Docker                                    |      23 |    0.01%
4     | docker --without-completions              |      13 |    0.00%
Total |                                           | 370,232 |  100.00%
==> install_on_request (30 days)
Index | Name (with options)                        |  Count |  Percent
-----:|--------------------------------------------|-------:|--------:
1     | docker                                     | 32,196 |   99.99%
2     | Docker                                     |      2 |    0.01%
Total |                                            | 32,198 |  100.00%
==> install_on_request (90 days)
Index | Name (with options)                        |  Count |  Percent
-----:|--------------------------------------------|-------:|--------:
1     | docker                                     | 83,896 |   99.99%
2     | Docker                                     |      3 |    0.00%
3     | docker --with-experimental                 |      3 |    0.00%
Total |                                            | 83,902 |  100.00%
==> install_on_request (365 days)
Index | Name (with options)                       |   Count |  Percent
-----:|-------------------------------------------|--------:|--------:
1     | docker                                    | 301,913 |   99.89%
2     | docker --with-experimental                |     305 |    0.10%
3     | Docker                                    |      23 |    0.01%
4     | docker --without-completions              |      12 |    0.00%
Total |                                           | 302,253 |  100.00%
==> build_error (30 days)
Index | Name (with options)                         | Count |  Percent
-----:|---------------------------------------------|------:|--------:
1     | docker                                      |     0 |    0.00%
```

**Comment by EricFromCanada** [comment]
The site only generates global standings for casks, fetched with `brew info --analytics --category=cask-install` — for now.

**Comment by MikeMcQuaid** [comment]
And we're live with all casks and their analytics: https://formulae.brew.sh

Great work on all this @brianmorton, @cmbernard333, @EricFromCanada! A real team effort from us all ❤️
