### ISSUE TITLE
php@7.3 /usr/local/etc/php/7.3/php-fpm.d/www.conf empty

### ISSUE THREAD

**Issue by whoacowboy** [Homebrew/formulae.brew.sh#134]
On a fresh install of php 7.3 the `php@7.3 /usr/local/etc/php/7.3/php-fpm.d/www.conf` file is  empty. I am not clear if this is by design, but it did cause me a few days of headache. 

If it isn't by design I am happy to create a pull request to fix it.

**Comment by MikeMcQuaid** [comment]
This is the wrong repository.
