### ISSUE TITLE
Aliases do not work when using brew search as browser quick search (site search)

### ISSUE THREAD

**Issue by ssbarnea** [Homebrew/formulae.brew.sh#1567]
Most site search can be configured to be quick searches in browser, so you could directly go to the right page.

Example from Chrome (same for most other browsers):

- Name: brew
- Shortcut: brew
- URL: `https://formulae.brew.sh/formula/%s`

How it works: when typing something like `brew foo` and press enter in browser search bar, intead of using the default search engine browser will open the URL `https://formulae.brew.sh/formula/foo`

Currently this work if your search is a perfect match for a brew recipe but it does not work with aliases. 

Example, quick search using `brew mc` will open a 404 page because `mc` is an alias for `midnight-commander`.

This could be addressed by providing HTTP redirects for aliases or by implementing a different query that does the redirection.

**Comment by SMillerDev** [comment]
The formula page isn't designed to be a search engine. There is a search implemented that does show aliasses.
