### ISSUE TITLE
Search problem: can't find syncthing

### ISSUE THREAD

**Issue by slokhorst** [Homebrew/formulae.brew.sh#175]
When searching for "syncthing":
<img width="595" alt="Screenshot 2019-09-10 at 12 52 49" src="https://user-images.githubusercontent.com/8083666/64608001-fe4f2e00-d3c9-11e9-8810-feb8a9a848c9.png">

The search doesn't show the [syncthing formula](https://formulae.brew.sh/formula/syncthing).

Edit: there seem to be many more formulae that can't be found, yet others work fine. Weird.

**Comment by MikeMcQuaid** [comment]
I've contacted Algolia support to see if they can help out.

**Comment by EricFromCanada** [comment]
The search is now showing both the formula and cask for `syncthing`, although it lists the cask under a "Homebrew Formulae" header.

**Comment by slokhorst** [comment]
The problem is back again.. Can't find syncthing nor e.g. python (#177).

**Comment by MikeMcQuaid** [comment]
This is not under our control. Please contact Algolia who hosts it.

**Comment by slokhorst** [comment]
Ok, I've contacted Algolia at docsearch@algolia.com (found at their [FAQ](https://community.algolia.com/docsearch/faq.html)). Lets hope they can fix it again this time.

**Comment by MikeMcQuaid** [comment]
Thanks @slokhorst ❤️ ! Keep us posted.

**Comment by s-pace** [comment]
👋 On it

**Comment by s-pace** [comment]
@slokhorst @MikeMcQuaid 

Issue solved. The crawl has been stuck and is now working as expected.

**Comment by slokhorst** [comment]
@s-pace thanks for the quick fix! I can confirm it's working nicely now. :smile:

**Comment by slokhorst** [comment]
@s-pace The issue has returned.. python and syncthing are missing again.

**Comment by s-pace** [comment]
👋 @slokhorst 

Crawl has been run and syncthing is now searchable. I will need to dig into this point to have a better understanding of why the crawl is that long I will keep you posted!

**Comment by MikeMcQuaid** [comment]
Thanks again @s-pace!
