### ISSUE TITLE
`/api/cask/${CASK_NAME}.json` is returning all zeros for the install count

### ISSUE THREAD

**Issue by varenc** [Homebrew/formulae.brew.sh#221]
Not sure if this is an issue with this code or some peculiarity that's just affecting the production site.

Anyway, you can see formulae.brew.sh is returning all zeros for the install stats of a particular cask:
```
> curl -s https://formulae.brew.sh/api/cask/dropbox.json | jq '.analytics'
{
  "install": {
    "30d": {
      "dropbox": 0
    },
    "90d": {
      "dropbox": 0
    },
    "365d": {
      "dropbox": 0
    }
  }
```

Whereas `/api/analytics/cask-install/30d.json` is returning the real stats
```
> curl -s  https://formulae.brew.sh/api/analytics/cask-install/30d.json  | jq '.items[] | select(.cask == "dropbox")'
{
  "number": 50,
  "cask": "dropbox",
  "count": "2,596",
  "percent": "0.36"
}
```

**Comment by EricFromCanada** [comment]
Yes, aggregation of stats for individual casks from homebrew/cask aren't implemented yet.

**Comment by EricFromCanada** [comment]
This has now been implemented in both the API and individual [cask pages](https://formulae.brew.sh/cask/dropbox):
```
$ curl -s https://formulae.brew.sh/api/cask/dropbox.json | jq '.analytics'
{
  "install": {
    "30d": {
      "dropbox": 2083
    },
    "90d": {
      "dropbox": 6551
    },
    "365d": {
      "dropbox": 29937
    }
  }
}
```

**Comment by MikeMcQuaid** [comment]
Well done @EricFromCanada 👏
