### ISSUE TITLE
Search: can't find "coreutils"

### ISSUE THREAD

**Issue by verhovsky** [Homebrew/formulae.brew.sh#232]
<img width="708" alt="Screen Shot 2020-01-19 at 3 29 58 PM" src="https://user-images.githubusercontent.com/5687998/72687960-084c1080-3ad1-11ea-9b5a-9511287403de.png">

https://formulae.brew.sh/formula/coreutils

Probably the same as #175

**Comment by MikeMcQuaid** [comment]
@s-pace any chance of another look? Thanks! ❤️
