### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by tanner0101** [Homebrew/formulae.brew.sh#234]
https://formulae.brew.sh has a JS search box for searching formula names, but not a dedicated page. This prevents users from linking directly to a search. 

I encountered this trying to update DuckDuckGo's [!bang](https://duckduckgo.com/bang) for Homebrew (`!brew`). It's currently linking to:

```
http://brewformulas.org/search?search%5Bterm%5D={{{s}}}
```

This URL is no longer owned by Homebrew and there's no suitable replacement.

I suggest either having `https://formulae.brew.sh?search=foo` automatically populate the search box or having a dedicated search page `https://formulae.brew.sh/search?q=foo`

**Comment by SMillerDev** [comment]
Since it's all Javascript and html I don't think a search page is possible but I'd happily review a pull request that prefills the search box.

**Comment by EricFromCanada** [comment]
It's easy to set the value of the search box from a URL parameter using the `URLSearchParams` interface; the issue I found is that the search box only appears if the insertion point is in the search field and after key has been pressed.

**Comment by DuBistKomisch** [comment]
:+1: this is pretty inaccessible, I was also looking for a way to fix the broken DDG bang. yarn has broken their package search in a similar way recently, hope the trend doesn't continue.

**Comment by SMillerDev** [comment]
We're not actually running any servers where we would be able to provide such a search function so this is the only way to even allow search. If you have a better solution I'd love to review it though.

**Comment by DuBistKomisch** [comment]
can't algolia run the search like now, but put the results in a page instead of a popup?

**Comment by SMillerDev** [comment]
As far as I can tell they don't provide that option. But I'm happy to be proven wrong.

**Comment by MikeMcQuaid** [comment]
You'll need to ask them. Regardless: submit PRs rather than 👍ing closed issues, thanks.
