### ISSUE TITLE
Setup for internal taps

### ISSUE THREAD

**Issue by JosephViolago** [Homebrew/formulae.brew.sh#26]
I'm curious on how to set this project up on an internal tap I have within a Github Enterprise.

I've looked at:
- [Homebrew/homebrew-core - .travis.yml](https://github.com/Homebrew/homebrew-core/blob/master/.travis.yml)
- [Homebrew/formulae.brew.sh - Rakefile](https://github.com/Homebrew/formulae.brew.sh/blob/master/Rakefile),
- [Travis CI](https://travis-ci.org/Homebrew/homebrew-core)

So I have a general idea of how the site is generated via jekyll and deployed. But I'd love to see if there's a guide somewhere.

I'd also like to learn more about:
- How to set this up using Github pages
- Considerations on how to deploy on other CI. (I don't know if TravisCI is allowed at my company.)
- How to set up analytics
  - looks like google analytics, but a lot of the details on it seem opaque

**Comment by MikeMcQuaid** [comment]
Sorry, this isn’t something we support. I’ll accept PRs to make this easier for you but this isn’t meant to be a generic service anyone can use.
