### ISSUE TITLE
Idea: Add `brew install <formula-name>` [copy-button] to the top of each package's webpage

### ISSUE THREAD

**Issue by mkolodny** [Homebrew/formulae.brew.sh#270]
✅ your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Install a formula (cocoapods).

## What happened (include screenshots)

I saw this webpage:

<img width="1680" alt="Screen Shot 2020-04-08 at 5 28 00 PM" src="https://user-images.githubusercontent.com/1448365/78845777-6b598f00-79be-11ea-91fc-c256587d93ed.png">

## What you expected to happen

I was looking for an easy way to copy the `brew install cocoapods` command to install cocoapods.

**Comment by SMillerDev** [comment]
Sounds like a good plan, I'd love to review your pull request for this.

**Comment by MikeMcQuaid** [comment]
Will review a PR for this, thanks.
