### ISSUE TITLE
Way to see 'newest' formulas?

### ISSUE THREAD

**Issue by symgryph** [Homebrew/formulae.brew.sh#29]
I used to use freshmeat to tell what the 'newest' software was. It used to be that I could 'query' brew for the newest formulas. How can this be done via api? Would be nice for a 'here are the newest formulas that have been added to brew'.

**Comment by MikeMcQuaid** [comment]
This isn't currently supported but a PR to add it would be welcome.

**Comment by MikeMcQuaid** [comment]
Closing this out because although I think it would be a good feature I can't think how it could be implemented.
