### ISSUE TITLE
Analytics Cask results polluted with items prefixed lnkd-

### ISSUE THREAD

**Issue by diimdeep** [Homebrew/formulae.brew.sh#293]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Look at [Analytics Cask page](https://formulae.brew.sh/analytics/cask-install/30d/)

## What happened (include screenshots)

There is hundreds of items prefixed with 'lnkd-'
It looks to me that someone is spammed analytics.
It does not look right to me.

<img width="890" alt="Screenshot 2020-05-20 at 15 43 49" src="https://user-images.githubusercontent.com/485713/82447536-1cb90d80-9ab1-11ea-8ae9-79bc92d05b3e.png">

**Comment by MikeMcQuaid** [comment]
@EricFromCanada Would you mind taking a look and seeing what you think is going on here?

**Comment by EricFromCanada** [comment]
I've made contact with who I correctly guessed might be behind those events, and they've added `HOMEBREW_NO_ANALYTICS=1` to their scripts.
