### ISSUE TITLE
Feature request for the site - show new, popular or just random formulae

### ISSUE THREAD

**Issue by Zejnilovic** [Homebrew/formulae.brew.sh#321]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

I am looking at packages at your website. Discovering. I discovered there is JEnv. Discovering new packages can lead to a lot of saved time.

## What happened (include screenshots)

Nothing happened.

## What you expected to happen

I think it would be great if there was a "feeling lucky" type of a thing where it would show new, popular or just random formulae. It would help people discover great tools and try out new things.

**Comment by MikeMcQuaid** [comment]
> I think it would be great if there was a "feeling lucky" type of a thing where it would show new, popular or just random formulae. It would help people discover great tools and try out new things.

https://formulae.brew.sh/analytics/install-on-request/30d/

**Comment by MikeMcQuaid** [comment]
(hopefully that provides what you'd like)
