### ISSUE TITLE
Help someone is having my gmail account and wifi using my hacked email through gethup

### ISSUE THREAD

**Issue by missajrcary3** [Homebrew/formulae.brew.sh#324]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

**Comment by SMillerDev** [comment]
I'm not sure how formulae.brew.sh has anything to do with this or how anyone could help you with this little information.

Here's an article from 2015 with information on how to avoid this in the future: https://www.businessinsider.com/how-to-avoid-being-hacked-2015-4
