### ISSUE TITLE
Idea: Copy install command to clipboard button

### ISSUE THREAD

**Issue by sidharthv96** [Homebrew/formulae.brew.sh#329]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

install a cask

## What happened (include screenshots)

I wasted some time waiting for brew update to finish and tell me that it was a cask and not a formula

## What you expected to happen

A button which copies the install command to clipboard, so all a user has to do is Cmd + V

This was discussed in #270

**Comment by sidharthv96** [comment]
@MikeMcQuaid had closed the previous issue.
Was that because of some technical issues?

If not, should I work on a PR ?

**Comment by GauthamGoli** [comment]
@sidharthv96  Feel free to open a Pull Request, we'll review it.

**Comment by MikeMcQuaid** [comment]
Closing the issue (we're not keeping feature requests open here) but, yes, will review a PR.
