### ISSUE TITLE
Spacing issue with Copy button

### ISSUE THREAD

**Issue by sidharthv96** [Homebrew/formulae.brew.sh#338]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)
Install a formula

## What happened (include screenshots)
![image](https://user-images.githubusercontent.com/10703445/94919937-f382a200-04d2-11eb-9c3a-be448eecf0db.png)

## What you expected to happen
No spacing around the install command.

**Comment by MikeMcQuaid** [comment]
@sidharthv96 If you're gonna submit a PR for this (🤞🏻) you can jump straight to that without needing to make an issue first!

**Comment by sidharthv96** [comment]
Oh sure!
Already have the fix, just trying to polish it a bit. Will submit the PR soon 👍
