### ISSUE TITLE
Incorrect formula for oracle-jdk

### ISSUE THREAD

**Issue by Manish-Giri** [Homebrew/formulae.brew.sh#369]
- [ ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Trying to download and install Oracle-jdk - https://formulae.brew.sh/cask/oracle-jdk#default

## What happened (include screenshots)

Error -
```sh
➜  ~ brew install --cask oracle-jdk
Error: Cask 'oracle-jdk' is unavailable: No Cask with this name exists.
```
![Screen Shot 2020-12-02 at 7 13 22 PM](https://user-images.githubusercontent.com/11348778/100946939-7c698a00-34d2-11eb-957e-41a78eeff2cc.png)

## What you expected to happen

Expected oracle-jdk to be installed

Platform - MacBook Pro running macOS Catalina 10.15.7

**Comment by SMillerDev** [comment]
This is an issue with your install. https://github.com/Homebrew/homebrew-cask/blob/master/Casks/oracle-jdk.rb still exists.
