### ISSUE TITLE
Deno 1.6.0_1 bottle 404 Not Found

### ISSUE THREAD

**Issue by balupton** [Homebrew/formulae.brew.sh#380]
## What you were trying to do (and why)

routine `brew update`

## What happened (include screenshots)

it tried to update from deno 1.5.3 to 1.6.0_1, and the 1.6.0_1 bottle URL 404s, so it had to build from source

```
==> Upgrading deno 1.5.3 -> 1.6.0_1 
==> Downloading https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "deno"
Download failed: https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

trying all these urls in the browser, they all 404

https://github.com/Homebrew/formulae.brew.sh/blob/04ce8f4ab5a84d22f7dda5eb63cd7a35d4a8f1ab/_data/formula/deno.json#L34-L46

whereas the urls from the previous commit do not 404

https://github.com/Homebrew/formulae.brew.sh/blob/5f72de2add802f54d58bc891e7539ad28ecce583/_data/formula/deno.json#L34-L46

## What you expected to happen

it to use the prebuilt binary, as I am on an intel macbook

**Comment by balupton** [comment]
According to https://github.com/Homebrew/discussions/discussions/299#discussioncomment-215791 this will fix it https://github.com/Homebrew/homebrew-core/pull/66920 once merged

**Comment by SMillerDev** [comment]
This is only for the website

**Comment by blixt** [comment]
I just had this issue when running `brew upgrade` on the command line, so it seems the issue is not yet resolved:

```
==> Upgrading deno 1.5.3 -> 1.6.0_1
==> Downloading https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "deno"
Download failed: https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```
