### ISSUE TITLE
Remove DependsOn: Mono for Radarr package

### ISSUE THREAD

**Issue by Qstick** [Homebrew/formulae.brew.sh#382]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What's the problem

Radarr 3.0 on Mac no longer has a mono dependency, thus this can be removed

https://github.com/Homebrew/formulae.brew.sh/blob/9826d8755ea250921cd05a0594affc0ca6b6b4f2/_data/cask/radarr.json#L19-L23

![image](https://user-images.githubusercontent.com/376117/102573478-88ea0700-40bc-11eb-9c59-9b64a56cb24e.png)

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/radarr.rb the code still says it does, you can make a pull request to correct it there.

**Comment by Qstick** [comment]
Seems like you guys have it wrong everywhere then
