### ISSUE TITLE
openshift-cli 4.6.0 installs oc version v4.2.0-alpha.0-657-g51011e4

### ISSUE THREAD

**Issue by bwoolf1** [Homebrew/formulae.brew.sh#403]
When I install the openshift-cli formula using Homebrew, currently v4.6.0 (which is also the latest version of OpenShift), the `oc` CLI that gets installed says its version is v4.2.0. It looks like the formula is installing the wrong version of the CLI. My laptop is running macOS Catalina 10.15.7. Others on my team have reproduced this problem on their machines. I can reproduce it very reliably (as shown below), it happens every time I uninstall and reinstall.

Is the openshift-cli formula incorrectly installing an old version of the CLI? If I'm doing something wrong, please let me know how use the formula correctly. Thank you for your help.

Here's what I'm doing to install the openshift-cli formula and check the version of the `oc` CLI that's installed:

```
$ brew install openshift-cli
==> Downloading https://homebrew.bintray.com/bottles/openshift-cli-4.6.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/94c8c7573dd37d9fc9107e5ac2f5476913c567bd164522e6216f235ad43975fe?response-content-disposition=attachment%3Bfilename%3D%22openshift-cli-4.6.
######################################################################## 100.0%
==> Pouring openshift-cli-4.6.0.catalina.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/openshift-cli/4.6.0: 5 files, 75.4MB
$ /usr/local/Cellar/openshift-cli/4.6.0/bin/oc version
Client Version: v4.2.0-alpha.0-657-g51011e4
Server Version: 4.5.24
Kubernetes Version: v1.18.3+fa69cae
```

For comparison, I've downloaded the `oc` CLI for OCP 4.5 and 4.6. They show a more expected version:
```
$ ./oc-4.5/oc version
Client Version: openshift-clients-4.5.0-202006231303.p0-18-g6082e941e
Server Version: 4.5.24
Kubernetes Version: v1.18.3+fa69cae
$ ./oc-4.6/oc version
Client Version: 4.6.9
Server Version: 4.5.24
Kubernetes Version: v1.18.3+fa69cae
```

# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

I'm trying to install the `oc` CLI by running `brew install openshift-cli`

## What happened (include screenshots)

As shown above, it installs successfully. But the `oc` version is not 4.6.x, it says it's 4.2.0. This seems like a very old version, not the current version.

## What you expected to happen

I expected the `oc` executable to be version 4.6.x. For example, a/the version for 4.5.x is openshift-clients-4.5.0-202006231303.p0-18-g6082e941e and for 4.6.x is 4.6.9 (as shown above).

**Comment by EricFromCanada** [comment]
This is for issues with the https://formulae.brew.sh/ site itself. Please post issues with formulae in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/issues).
