### ISSUE TITLE
Display Apple Silicon support (or lack of support) in a clearer way

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/formulae.brew.sh#407]
Several users have suggested that, with the Apple Silicon transition under way, it would be good to indicate more clearly the support for that new platform on our formula pages.

Right now, going at https://formulae.brew.sh/formula/llvm you need to know to look for `arm64_big_sur` in the bottles. Most people wouldn't know that, and the information is somewhat hidden for them.

We could instead have:

> stable | ✅ | 11.0.0
> -- | -- | --
> Apple Silicon | ✅ | *supported*
> head | ⚡️ | HEAD
> bottle | 🍾 | big_sur, arm64_big_sur, catalina, mojave

Or some other way to display this status in a clearer way.

**Comment by fxcoudert** [comment]
I tried to figure out how to do that, in order to open a pull request. But I don't know what language those `.in` files are written in, so I had no idea how to do that.

**Comment by MikeMcQuaid** [comment]
@EricFromCanada Any thoughts on this?

**Comment by EricFromCanada** [comment]
I'd like to do a larger layout cleanup to more clearly distinguish labels from values (example: [NixOS packages](https://search.nixos.org/packages?channel=20.09&show=libpng&from=0&size=30&sort=relevance&query=libpng)) but I can throw in a quick fix for the meantime. I'd lean towards splitting the "bottle" line into lines for "Intel bottles" and "Apple Silicon bottles".

**Comment by MikeMcQuaid** [comment]
@EricFromCanada A quick fix sounds good. I think naming the OSs in a "prettier" fashion would be good and using the presence of "Apple Silicon" (and perhaps others?) to state "supported on macOS ..." would also be good.
