### ISSUE TITLE
Bottle list table is confusing for some users

### ISSUE THREAD

**Issue by carlocab** [Homebrew/formulae.brew.sh#426]
I've already seen two instances of users mistakenly interpreting the fact that the bottle list table says "Apple Silicon" as an indicator that Apple Silicon is supported. (e.g. https://github.com/Homebrew/discussions/discussions/925, https://github.com/Homebrew/discussions/discussions/878)

It would be nice if the table were easier to interpret for readers who aren't paying attention. I'm not sure about what the best way to do this would be, but some ideas I had were:

1. Put a strike through "Apple Silicon" (e.g. ~~Apple Silicon~~) when no bottle is available.
2. Add the 🍾 emoji in the table somewhere when that architecture/OS version has a bottle.

I may be partial to the second one because I do miss the 🍾 emoji a little. That said, it may not be obvious enough for the readers I'm thinking of.

Cf. #408

**Comment by Rylan12** [comment]
How about I wouldn't be opposed to a simple `Not supported` (probably in italics to indicate that it's not an OS name).

Another option may be to simply say `Not Supported` if it's not supported. I'm a little torn about this as it's not as easy to tell at a glance whether it's supported or not.

<img width="612" alt="Screen Shot 2021-02-24 at 5 16 53 PM" src="https://user-images.githubusercontent.com/32525609/109073314-36345900-76c4-11eb-82ff-523ef277bd6c.png">

**Comment by jonchang** [comment]
I have a solution for this. Need to check it (this repo takes 10 mins to build for each change on my machine...) but I think it'll look good. Pull request soon.
