### ISSUE TITLE
Link to the formula itself in the formula page

### ISSUE THREAD

**Issue by waldyrious** [Homebrew/formulae.brew.sh#44]
Currently a formula page only has a link to the actual software's homepage, but there's no link to the formula itself (e.g. `https://github.com/Homebrew/homebrew-core/blob/master/Formula/formula-foo.rb`).

It would be nice to provide this link as well so users could inspect the code of the formulas.

**Comment by waldyrious** [comment]
(commit 1b1f110 seems to be related, but I'm not sure)

**Comment by koraktor** [comment]
Thanks, sounds like a good idea.

PS: Commit 1b1f11003e74f2eaa267e4fce2dcb4b3e7d6347e is not related to the front-end, it is related to symlinking during the import process.
