### ISSUE TITLE
Formulae search broken

### ISSUE THREAD

**Issue by NeighbourDYY** [Homebrew/formulae.brew.sh#442]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Searching for formulas and casks

## What happened (include screenshots)

The exact match does not show in the drop-down list; only other matches show up, e.g.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44958165/113487894-3fad9f80-9480-11eb-8d66-809ad342ddc0.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44958165/113487855-12f98800-9480-11eb-8c9f-5b34b5cb0352.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44958165/113487808-c4e48480-947f-11eb-800a-66bbae892491.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/44958165/113487827-e5acda00-947f-11eb-85bc-2820bf025437.png">

## What you expected to happen

formula/cask with exact name match shows at the top of the list.

**Comment by Rylan12** [comment]
Thanks for the report. I can reproduce this but I'm stepping into some territory I'm not super familiar with. It looks like we use [DocSearch by Algolia](https://docsearch.algolia.com) for the search, so I wonder if this needs to be reported to them instead (which I'll gladly do if needed).

@EricFromCanada I figure you'll know more about this and can advise whether this is something we need to fix on our end or report to Algolia.

**Comment by SMillerDev** [comment]
See https://github.com/Homebrew/formulae.brew.sh/issues/308 for earlier issues.

**Comment by Rylan12** [comment]
Hmm. That does seem to me like it's an issue on their end. It looks like `@s-pace` (who helped us last time) no longer works at Algolia and doesn't appear to be very active.

Worth opening an issue in [algolia/docsearch-configs](https://github.com/algolia/docsearch-configs) or [algolia/docsearch-scraper](https://github.com/algolia/docsearch-scraper) (or elsewhere)?

**Comment by EricFromCanada** [comment]
Is there a way to host the [config file](https://github.com/algolia/docsearch-configs/blob/master/configs/brew_all.json) on our end so we don't have to bug them each time the site's document structure changes?

**Comment by SMillerDev** [comment]
I guess we could make a PR against that file.

**Comment by Rylan12** [comment]
We could [run our own instance](https://docsearch.algolia.com/docs/run-your-own) it looks like (haven't really looked at what this would entail but it seems like it could easily be done in a GitHub Action.

> each time the site's document structure changes?

Has that happened? If so, a PR might be all we need.

**Comment by SMillerDev** [comment]
> We could run our own instance it looks like (haven't really looked at what this would entail but it seems like it could easily be done in a GitHub Action.

We don't have an algolia account though. That's hosted by Algolia themselves.

**Comment by Rylan12** [comment]
We do have an [API key](https://github.com/Homebrew/brew.sh/blob/b2d447012c4e39e7625c004586b87d7fa7a51403/_layouts/base.html#L3), though, so I wonder if we do have an account.

**Comment by Rylan12** [comment]
I sent an email to the DocSearch folks at Algolia. I will update this thread when I receive a response.

**Comment by shortcuts** [comment]
Hi guys, I've pushed an update to fix the direct matches results https://github.com/algolia/docsearch-configs/pull/3922, which is now live and should fix the above issue.

All the details about the other questions have been sent by email to @Rylan12 

Feel free to ping me if you see some more issues :D

**Comment by MikeMcQuaid** [comment]
Confirmed fixed, thanks @shortcuts!

**Comment by Rylan12** [comment]
Awesome! Thanks, @shortcuts!
