### ISSUE TITLE
api links are now 'linuxbrew'

### ISSUE THREAD

**Issue by pvtmert** [Homebrew/formulae.brew.sh#45]
i don't know if thats the intended result but all bottle links are now linuxbrew.bintray.com instead of homebrew.bintray.com

you can see them at: 
https://formulae.brew.sh/api/formula.json

**Comment by MikeMcQuaid** [comment]
@sjackman I guess a Linuxbrew merge issue? Mind taking a look?

**Comment by sjackman** [comment]
My best guess is that this web service `formulae.brew.sh` is running on a Linux box, and so the default bottle domain is `linuxbrew.bintray.com`. Setting `HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com` may resolve the issue.
