### ISSUE TITLE
No Apple Silicon bottles available: pdftk-java, pandoc

### ISSUE THREAD

**Issue by kkbt** [Homebrew/formulae.brew.sh#467]
## What you were trying to do (and why)

Trying to install formulae pdftk-java and pandoc.
Other formulae were installed without any problem.

## What happened (include screenshots)

Error message "no bottle available!" appeared.

Log:

% brew install pdftk-java
Error: pdftk-java: no bottle available!
You can try to install from source with:
  brew install --build-from-source pdftk-java
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
% brew install pandoc    
Error: pandoc: no bottle available!
You can try to install from source with:
  brew install --build-from-source pandoc
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
% sw_vers 
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241

## What you expected to happen

Proper installation.

Bottles seem to be available for macOS Big Sur (= macOS 11) for Intel only, not for Apple Silicon which I have:

- [https://formulae.brew.sh/formula/pdftk-java](https://formulae.brew.sh/formula/pdftk-java)
- [https://formulae.brew.sh/formula/pandoc](https://formulae.brew.sh/formula/pandoc)

For example, this formula provides bottle (binary package) installation support for Apple Silicon Big Sur and is installed without any problem:

- [https://formulae.brew.sh/formula/rsync](https://formulae.brew.sh/formula/rsync)

**Comment by SMillerDev** [comment]
If there is no bottle it means the software doesn't build on ARM.

**Comment by kkbt** [comment]
I have reported this to the software packages:

- [https://github.com/jgm/pandoc/issues/7294](https://github.com/jgm/pandoc/issues/7294)
- [https://gitlab.com/pdftk-java/pdftk/-/issues/92](https://gitlab.com/pdftk-java/pdftk/-/issues/92)

As a workaround for pdftk, this package may work:

- [https://apple.stackexchange.com/a/420712/417876](https://apple.stackexchange.com/a/420712/417876)

**Comment by kkbt** [comment]
As a preliminary solution, I was successful in installing the Intel version of homebrew in /usr/local (in parallel to the M1 version in /opt/homebrew) using Apple's Rosetta 2 layer. The Intel packages (homebrew formulae) seem to work without any problem on the Apple M1 architecture. Both pdftk and pandoc work even without prefixing 'arch -x86_64' (e.g., the command 'pandoc sample.md -o sample.html' as in the example linked below).


Commands:

arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
alias ibrew='arch -x86_64 /usr/local/bin/brew'
ibrew analytics off
ibrew install pdftk-java
ibrew install pandoc


Further information:

- [https://soffes.blog/homebrew-on-apple-silicon](https://soffes.blog/homebrew-on-apple-silicon)
- [https://github.com/jgm/pandoc/issues/6960#issuecomment-778698895](https://github.com/jgm/pandoc/issues/6960#issuecomment-778698895)
