### ISSUE TITLE
Focus search box when press `/`

### ISSUE THREAD

**Issue by sh-cho** [Homebrew/formulae.brew.sh#556]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Move cursor using keyboard to search box

## What happened (include screenshots)

![image](https://user-images.githubusercontent.com/11611397/134876919-dc36c781-d8ea-4caf-95e4-e0849ad30dbb.png)

I should keep press tab until I find "Search Homebrew Formulae" input box.

## What you expected to happen

![image](https://user-images.githubusercontent.com/11611397/134875937-968a4ccb-8190-420a-8b4c-066dc84bb6b4.png)

Move focus to search box when press '/' or something just like Google. It's really useful.

I tried to fix this myself but I don't understand how this website's search box has been made and where to put some js file.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry.
