### ISSUE TITLE
Do not show removed formula

### ISSUE THREAD

**Issue by colindean** [Homebrew/formulae.brew.sh#58]
http://formulae.brew.sh/formula/rubber is showing a formula that [has been removed](https://github.com/Homebrew/homebrew-tex/commit/d8838e09147dff8b8f2a7756e218544a0c9d9f72) from its tap, [homebrew-tex](https://github.com/Homebrew/homebrew-tex/), which itself is deprecated.

Raised by `bkircher` on IRC around 06:55:00 EDT today.

**Comment by koraktor** [comment]
To be honest. This should be automatically handled [during import](https://github.com/Homebrew/formulae.brew.sh/blob/master/lib/tap_import.rb#L335). (That line will hide a tap once all formulae where removed, which is the case for homebrew-tex.)

I have no idea what didn’t work here, but I’m currently unable to debug this in detail.

See PR #61 for a more centralized approach.

**Comment by colindean** [comment]
#61 looks like a good way to handle it. Thanks.
