### ISSUE TITLE
Show installation command tip on formula page

### ISSUE THREAD

**Issue by colindean** [Homebrew/formulae.brew.sh#59]
Dovetailing off of #44, which is linking to the formula itself, it'd be great if formula pages displayed an installation command line on them. This is especially relevant for automatic tapping.

Something that's in core and thus the formula for which is already installed could be given as something like `brew install ledger`. Something in a tap, e.g. http://formulae.brew.sh/formula/ajp-nginx-module,  could be presented `brew install homebrew/nginx/ajp-nginx-module`.

**Comment by MikeMcQuaid** [comment]
I'm personally 👎 on this because by 2018 there will be no more official, non-depracted taps.

**Comment by colindean** [comment]
I'm a little out of the loop. Do you mean that _everything_ will need to be installed fully namespaced or that _nothing_ will need to be installed fully namespaced? Or something else?

**Comment by MikeMcQuaid** [comment]
I mean that `formulae.brew.sh` will not/should not include any formulae that require the namespaced install.

**Comment by colindean** [comment]
Understood. I think it could still be quite handy to be able to copy and paste the complete command line necessary to install the package on the page.

**Comment by colindean** [comment]
30 second mockup:

![screen shot 2017-10-09 at 18 28 21](https://user-images.githubusercontent.com/197224/31361120-b329c868-ad1f-11e7-98b3-faac893da86c.png)

```css
#install pre {
    border: 1px solid #f9d094;
    padding: 0.4em;
    background: #222;
}
#install pre:before {
  content: "$ ";
}
```

```html
<div id="install">
      <h2>Install with</h2>
      <pre>brew install ajp-nginx-module</pre>
</div>
```

**Comment by koraktor** [comment]
@MikeMcQuaid :-1: for the taps. But what about the feature in general?

A long time ago, I thought about writing a small app that could handle custom URLs to directly install formula by clicking a link. I dropped that idea pretty quickly because I was unable to detect the app inside the browser. I would deem this a must for a fluent UI/UX.

We shouldn’t add only text, IMHO there should be at least a copy button to make it comfortable.

**Comment by MikeMcQuaid** [comment]
I don't feel strongly either way about the text but it does seem like a bit of a rabbithole; if people can't copy paste the title and go `brew install $PASTE`?

**Comment by MikeMcQuaid** [comment]
I don't feel strongly either way about the text but it does seem like a bit of a rabbithole; if people can't copy paste the title and go `brew install $PASTE`?

**Comment by koraktor** [comment]
If there’s no strong argument *for* adding this, I guess there’s no reason to add it and additionally clutter the formula pages. That’s another reason why I didn’t add it, yet.

**Comment by MikeMcQuaid** [comment]
I agree @koraktor, sorry @colindean!

**Comment by colindean** [comment]
I'm okay with this not going in. Thanks for considering it, though.
