### ISSUE TITLE
Drop deprecated and migrated repos from indexed taps

### ISSUE THREAD

**Issue by colindean** [Homebrew/formulae.brew.sh#60]
[Homebrew-tex](https://github.com/Homebrew/homebrew-tex) is deprecated and now contains no formulae. It should not be indexed on `formulae.brew.sh` unless only the [migrated formulae](https://github.com/Homebrew/homebrew-tex/blob/master/tap_migrations.json) are indexed.

**Comment by MikeMcQuaid** [comment]
Also: apache and fuse and emacs was migrated.

**Comment by colindean** [comment]
Oooh. I'll change the title to be more inclusive.
