### ISSUE TITLE
Support and enforce HTTPS

### ISSUE THREAD

**Issue by Krinkle** [Homebrew/formulae.brew.sh#63]
* [:lock: **https**://brew.sh](https://brew.sh/)
* [:lock: **https**://docs.brew.sh](https://docs.brew.sh/)
* [:lock: **https**://discourse.brew.sh](https://discourse.brew.sh/)
* <http://formulae.brew.sh>

**Comment by MikeMcQuaid** [comment]
This requires a paid Heroku plan which we do not have the resources for.

**Comment by Krinkle** [comment]
What about Cloudfare's free CDN plan that includes SSL? (Very popular among sites hosted with GitHub Pages with a custom domain).

Or Let's Encrypt, if you prefer your own hosting?

I'm aware many (most) providers still provide paid options for SSL, but if you're in a paid plan now that doesn't also allow you to to your own (e.g. Let's Encrypt), the you're the service is imho not worth paying for.

**Comment by koraktor** [comment]
@Krinkle I don’t have any experience with Cloudflare (or CDNs in general) especially when combined with Heroku. I’d think this is a pretty complex environment that’s probably not working with the free plan.

Do you have any resources (documentation, blog posts) that demonstrate such a setup?

**Comment by Krinkle** [comment]
The paid Heroku plans include SSL support (including the Hobby plan, no 20$ add-on required). This actually uses Let's Encrypt internally: <https://devcenter.heroku.com/articles/automated-certificate-management>

If using a free Heroku plan, you have three options:

1. Let's Encrypt via HTTP: Add a request handler to you Rails app for `/.well-known/acme-challenge/*` urls and respond either with a pre-configured environment variable that you update once a month through your configuration dashboard, or use a Ruby acme-client to generate it on-demand. After initial set-up, no code changes required.
2. Let's Encrypt via DNS: Add a DNS TXT entry for your domain. This will need to be updated via a command-line utility from your machine once a month. No code changes. 
2. Use CloudFare's free CDN and SSL plan: <https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku>.

The last is probably the easiest, although it means there will still be an insecure connection between CloudFare and Heroku.

The Hobby plan from Heroku is 7$ a month. I would imagine with all the crowdfunding support for the ovearall Homebrew project, this would be within budget?

Alternatively, there's a 4th radical approach, which matches the other Homebrew sites: Convert the codebase to Jekyll and generate the site statically from a Travis CI build. This can be securely generated and committed to the gh-pages branch and secured with custom domain the same way as the brew.sh are. For up-to-date analytics data, you can even use Travi's new free [cron](https://docs.travis-ci.com/user/cron-jobs/) feature to trigger site generation without the need for dummy git commits.

**Comment by MikeMcQuaid** [comment]
Will 1) autorenew without intervention? 2) is a non-starter given it'll require manual intervention. I've played with 3) for brew.sh in the past and I couldn't get it to work properly or consistently so I'm personally 👎 on trying again.

> I would imagine with all the crowdfunding support for the Homebrew project, that this site would not be running on a free Heroku plan. If not at Heroku, then perhaps you could instead run this site via one of your sponsors. Such as Netlify?, or DigitalOcean?

That would require someone e.g. keep the system packages secure and up-to-date so we'd rather avoid moving from Heroku for anything that's working OK already.

> Alternatively, there's a radical option: Convert the codebase to Jekyll and generate the site statically from a Travis CI build

If you can submit a PR to do this that would be interesting but I don't imagine @koraktor or I have any plans to do this ourselves, sorry.

**Comment by paulmelnikow** [comment]
You could also consider Zeit's OSS plan: https://zeit.co/pricing

**Comment by Krinkle** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by koraktor** [comment]
@Krinkle formulae.brew.sh is not a GitHub Pages site, so there’s nothing we can activate.

We are in the process of rebuilding it as a static site that could be hosted on GHP. So we’ll have that option later.

**Comment by Krinkle** [comment]
@koraktor Good point. I knew that from before actually, but forgot. Thanks for replying, and awesome to hear you're working on making it statically generated!
