### ISSUE TITLE
Idea: display the path for executables installed by formulae

### ISSUE THREAD

**Issue by ConorSheehan1** [Homebrew/formulae.brew.sh#641]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)
Install 7zip https://formulae.brew.sh/formula/sevenzip

## What happened (include screenshots)
I couldn't find the binary path that'd be installed. I had to go to the sourcecode to see it's 7zz.
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sevenzip.rb#L32
![Screenshot 2022-03-24 at 11 38 22](https://user-images.githubusercontent.com/16896053/159909055-238e5b34-32d6-4116-b8ae-71e7d0f96db4.png)

## What you expected to happen
It would be really helpful to display the path for executables installed by formulae. e.g.
![Screenshot 2022-03-24 at 11 41 38](https://user-images.githubusercontent.com/16896053/159909071-626bae64-83c2-4ea8-aacd-5eca7f44ad0c.png)

**Comment by SMillerDev** [comment]
`brew ls sevenzip` will display all files a formula installed. But I think that would be far too much information to display on the website.

For example for `boost`: `/usr/local/Cellar/boost/1.78.0_1/include/boost/ (15026 files)`

**Comment by MikeMcQuaid** [comment]
Passing on this.
