### ISSUE TITLE
DuckDuckGo Bang is broken -> what is the search page?

### ISSUE THREAD

**Issue by MagicLegend** [Homebrew/formulae.brew.sh#657]
- [X] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

The DuckDuckGo `!brew` bang is broken.

## What happened (include screenshots)

Searching for `!brew php` leads to `http://brewformulas.org/search?search%5Bterm%5D=php`, which is a dead site. (Warning: Chinese spam at the main domain)

## What you expected to happen

Come up with search results (or the direct page in case of a match), and lead me to `https://formulae.brew.sh/formula/php#default`.

## Why am I submitting this here

Updating a bang can be done at https://duckduckgo.com/newbang. However, I can't quickly figure out what the url structure of the _search_ page would be. Otherwise the bang would only work for direct matches. I would expect it to behave like the `!npm` bang, which leads to `https://www.npmjs.com/search?q={{{s}}}`. I see the searching is handled by algolia, is there a way to hook into that perhaps?

## Other info

I am aware of the `!brewf` bang, which leads to `https://formulae.brew.sh/formula/{{{s}}}`. However, for non-existing packages this will show the Github Pages 404 page. E.g.: https://formulae.brew.sh/formula/qwer. I would want it to show a search page, and give me these results:
![image](https://user-images.githubusercontent.com/3169104/180159936-93223973-b78d-4a48-a659-bee3ce0c0c0d.png)

**Comment by SMillerDev** [comment]
There is no search page so this is not possible.

**Comment by EricFromCanada** [comment]
Over a year ago I implemented a partial workaround where the `search` parameter contents is pre-filled in the search bar. However, all of my attempts to contact DuckDuckGo and have the `!brew` bang updated to `https://formulae.brew.sh/?search={{{s}}}` have gone unanswered.

**Comment by MagicLegend** [comment]
Oh that's great to see! Perhaps it DDG receives more requests to change a certain bang, it might get through the system faster? I have submitted it myself as well regardless :)
