### ISSUE TITLE
formulae.brew.sh not successfully deployed with latest data

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [Homebrew/formulae.brew.sh#683]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

[We](https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles) are downstream mirrors of homebrew-bottles so we consume formulae.brew.sh. We found that the json it provides is inconsistent with the homebrew-core.

Related issue: https://github.com/tuna/issues/issues/1650

## What happened (include screenshots)

homebrew-core updated libidn2 yesterday in https://github.com/Homebrew/homebrew-core/commit/8d4351d0179e5c57bdb6235479ebcb43669188b3, however, the json provided in https://formulae.brew.sh/api/formula/libidn2.json is not updated.

![Screenshot2023-01-19-18:01:35](https://user-images.githubusercontent.com/19512674/213413197-d7a48084-681d-4082-be60-6201d976f6fb.png)

After some investigation, I found that the content generated in CI is updated (see the data-core.zip artifacts in https://github.com/Homebrew/formulae.brew.sh/actions/runs/3956901119)

![Screenshot2023-01-19-18:05:01](https://user-images.githubusercontent.com/19512674/213413935-50e0cb07-7c97-47ab-b190-cffe56dfc709.png)

I assume that the generated contents are not successfully deployed.

## What you expected to happen

formulae.json is consistent with homebrew-core.

**Comment by MikeMcQuaid** [comment]
It was updated an hour ago (https://github.com/Homebrew/formulae.brew.sh/actions/workflows/scheduled.yml). It's expected there may be a slight lag.

**Comment by ZenithalHourlyRate** [comment]
> It was updated an hour ago

I do know that github actions have updated it.

> It's expected there may be a slight lag.

Is this lag introduced by CDN? I can still see that in https://formulae.brew.sh/api/formula/libidn2.json the rebuild field is not updated.

**Comment by MikeMcQuaid** [comment]
@ZenithalHourlyRate Hmm, weird.
@SMillerDev could you check this out? Perhaps something with the change in generation approach?

**Comment by SMillerDev** [comment]
I suspect the unpacking of the archives is causing some issues. Let me check.

**Comment by ZenithalHourlyRate** [comment]
It is still not updated.

**Comment by MikeMcQuaid** [comment]
@SMillerDev May be worth reverting all these changes and pairing on it at FOSDEM. I'm concerned this may end up breaking `HOMEBREW_INSTALL_FROM_API`.

**Comment by SMillerDev** [comment]
It's now reporting `"rebuild": 1`, I think that last commit fixed it.

**Comment by MikeMcQuaid** [comment]
Thanks for fixing @SMillerDev!
