### ISSUE TITLE
Use exact match as first item in the search result

### ISSUE THREAD

**Issue by 365cent** [Homebrew/formulae.brew.sh#700]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

I just noticed that the current version of package is now display at the bottom of search result after shift to algolia, I suggest to make exact match as default and display as first item in the search result

## What you were trying to do (and why)

I am trying to search for a package on brew.sh, but the current version of package is shown at the end of result.

## What happened (include screenshots)

<img width="588" alt="Screenshot 2023-02-01 at 2 56 55 PM" src="https://user-images.githubusercontent.com/74791570/216150080-7dbb14bb-7e62-4d58-9350-42879cb6bc86.png">

## What you expected to happen

The current version displays as first item on the list.

**Comment by Bo98** [comment]
I think I've fixed this. I've applied an alphabetical sort on tiebreakers, which is not the most ideal, but it might be the only thing possible.
