### ISSUE TITLE
Publish API tarball for mirror sites 

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [Homebrew/formulae.brew.sh#730]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

[We](https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/) are downstream mirrors of homebrew.

As brew recently switched to API endpoint, we are [willing](https://github.com/tuna/issues/issues/1666) to mirror these API as well. However, these APIs contain many files (for `https://formulae.brew.sh/api/formula/${FORMULA}.json` I can see there are 6506 jsons in total) and `curl` them one by one might be assumed as DoS.

## What you expected to happen

Provide a tarball such as `https://formulae.brew.sh/api.tgz` such that when decompressed, we can get the whole content of `https://formulae.brew.sh/api/`.

**Comment by MikeMcQuaid** [comment]
@ZenithalHourlyRate The GitHub Pages artefact on e.g. https://github.com/Homebrew/formulae.brew.sh/actions/runs/4114701203 should get you want you want here.

**Comment by ZenithalHourlyRate** [comment]
> https://github.com/Homebrew/formulae.brew.sh/actions/runs/4114701203

Depending on this sounds like depending on a private API.

I could access artifacts via https://api.github.com/repos/Homebrew/formulae.brew.sh/actions/artifacts and filter by `name == github-pages` and `workflow_run.head_branch == master`, but if further changes in CI/repo are done, would the artifact name and branch name remain unchanged?

**Comment by ZenithalHourlyRate** [comment]
> I'm not sure what other method we can provide

Well, I think simply another line of command in the CI that creates `api.tgz` could suffice our need.

> This would only change if we change our deployment mechanism.

I do not know what artifacts in #934 would look like. I'll wait for #934.

**Comment by SMillerDev** [comment]
That pull request won't change the formulae.brew.eh deployments

**Comment by MikeMcQuaid** [comment]
> Well, I think simply another line of command in the CI that creates `api.tgz` could suffice our need.

We already create this. Where do you expect this file to be?

**Comment by ZenithalHourlyRate** [comment]
> We already create this. Where do you expect this file to be?

> Provide a tarball such as `https://formulae.brew.sh/api.tgz`

Could it be provided here?

**Comment by MikeMcQuaid** [comment]
> Could it be provided here?

@ZenithalHourlyRate No because based on our deployment process the `api.tgz` would have to include itself.

Considering the artefact upload here to be the API for this, passing on going beyond that, sorry.
