### ISSUE TITLE
After Latest Merge Not Able to download HomeBrewy

### ISSUE THREAD

**Issue by daksh-semwal-kr** [Homebrew/formulae.brew.sh#770]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

I was trying to install. Homebrew

## What happened (include screenshots)
 Homebrew installation fails
<img width="716" alt="image" src="https://user-images.githubusercontent.com/98511393/220095856-102e383e-d527-44fe-8173-33a4f7ea75f8.png">

## What you expected to happen

I expected installation to happen

**Comment by EricFromCanada** [comment]
https://github.com/orgs/Homebrew/discussions/666
