### ISSUE TITLE
How frequently do new days get added to the Analytics?

### ISSUE THREAD

**Issue by hermanschaaf** [Homebrew/formulae.brew.sh#796]
Hi, not sure if this is the right place to raise this issue, please redirect me if not.

I have been running a script that fetches the latest analytics API data on a daily basis for the last few days. I'm interested in analyzing the trends of Homebrew formula installs. Since starting the fetches a week ago, I've noticed that in every single case the number of installs reported by the 30d endpoint has been going down every day.

Here are some examples:

![Screenshot 2023-03-02 at 11 28 59](https://user-images.githubusercontent.com/1121616/222416367-8a900ff7-a2e2-4fc5-9fd8-e4245f1e86be.png)
![Screenshot 2023-03-02 at 11 28 13](https://user-images.githubusercontent.com/1121616/222416372-ce067765-d4e6-42e6-9ef2-e36a9860a8fa.png)
![Screenshot 2023-03-02 at 11 26 26](https://user-images.githubusercontent.com/1121616/222416375-3c273fbf-3c89-4ed1-b692-422443a001cf.png)

This consistent, linear downwards trend seems to be the case for just about all the formulae I looked at. I'm finding it hard to attribute to coincedence: is there maybe something askew with the data? My guess would be that the data being served for the past 30 days, but recent days have not been added to the totals.

**Comment by MikeMcQuaid** [comment]
Sorry, we can't handle this sort of data analysis.

It may be that some of these folks have opted-out of Google Analytics (or analytics in general).

**Comment by MikeMcQuaid** [comment]
> not that folks started opting out all at the same time, at about the same rate every day, for all formulae.

We introduced a new variable and announced it widely so: this sounds like exactly what is happening.

> If this is not the right place to ask, do you know where I can raise data quality issues related to the data provided by the formulae API?

There isn't one.

All the code is open source. We'll review PRs if you find a bug and can fix them.

**Comment by hermanschaaf** [comment]
Ah I see, thanks! Might just have been bad timing on my part then :)
