### ISSUE TITLE
Homebrew install events tracking is broken

### ISSUE THREAD

**Issue by skapoor-coatue** [Homebrew/formulae.brew.sh#830]
The [homebrew install events tracking ](https://formulae.brew.sh/analytics/install/30d/) is undercounting install events in the events tracking service (see [30d install events](https://formulae.brew.sh/analytics/install/30d/), [90d install events](https://formulae.brew.sh/analytics/install/90d/)). The install counts look significantly lower than expected. 

## What you were trying to do (and why)
We track homebrew install events using the install events APIs (eg. [30d installs](https://formulae.brew.sh/analytics/install/30d/), [90d installs](https://formulae.brew.sh/analytics/install/90d/)). We collect these metrics on regular basis to build a point-in-time tracking of install events for trailing 30d, and 90d. 

## What happened (include screenshots)
We see a significant drop in the install counts for all formulae. The issue seems to have started sometime in mid-February. See the following screenshot as an example:

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/48841433/234063207-27a4e7e0-b38f-4057-9721-979a987f567a.png">

This data is pulled using [Linux install events 30d endpoint](https://formulae.brew.sh/api/analytics-linux/install/30d.json). Notice the drop in `count`, `total_items`, `total_count` from February to today.

## What you expected to happen
We expect the items & count metrics to be in line with the historical values.

**Comment by MikeMcQuaid** [comment]
> The issue seems to have started sometime in mid-February.

- There was some double-counting going on that was fixed at that time
- This is when we announced we were moving to InfluxDB and provided a new opt-out just for Google Analytics that it is likely a non-trivial number of people are using.

Nothing we can do here until we migrate to InfluxDB analytics 🔜.

**Comment by fxcoudert** [comment]
@MikeMcQuaid looking at analytics for big formulas (openssl, gcc, python), the drop is not likely to be caused simply by people opting-out. For Python:

```
install: 4,459 (30 days), 551,298 (90 days), 1,682,128 (365 days)
```

that would mean that 97.5% of users have used the new opt-out. That seems very unlikely.

**Comment by MikeMcQuaid** [comment]
@fxcoudert Analytics work is being tracked in https://github.com/Homebrew/brew/issues/13211.
