### ISSUE TITLE
unable to upgrade 

### ISSUE THREAD

**Issue by gasova** [Homebrew/formulae.brew.sh#833]
Hi, 

There is a problem with libtiff, upgrading packages fails, and is stuck because libtiff URL returns 503 error, in this cases home-brew should continue with other packages 

`
› brew upgrade        
==> Upgrading 14 outdated packages:
libtiff 4.4.0_1 -> 4.5.0
little-cms2 2.14 -> 2.14_1
gh 2.27.0 -> 2.28.0
ghostscript 10.01.1 -> 10.01.1_1
mono-libgdiplus 6.1_1 -> 6.1_2
mpfr 4.2.0 -> 4.2.0-p4
openjpeg 2.5.0 -> 2.5.0_1
gdk-pixbuf 2.42.10 -> 2.42.10_1
glib 2.76.1 -> 2.76.2
webp 1.3.0 -> 1.3.0_1
gtk4 4.10.3 -> 4.10.3_1
gd 2.3.3_4 -> 2.3.3_5
symfony-cli/tap/symfony-cli 5.5.2 -> 5.5.3
imagemagick 7.1.1-8 -> 7.1.1-8_1
==> Fetching libtiff
==> Downloading https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.5.0
Error: libtiff: Failed to download resource "libtiff_bottle_manifest"
Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-82-gb2aa6fb\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --header Accept:\ application/vnd.oci.image.index.v1\+json --header Authorization:\ Bearer\ QQ== --fail --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/libtiff/manifests/4.5.0` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 503
HTTP/2 503 
content-type: application/json
docker-distribution-api-version: registry/2.0
date: Thu, 27 Apr 2023 09:23:45 GMT
content-length: 68
x-github-request-id: C570:A4DD:4AB7F9:4D3DD5:644A3F19

curl: (22) The requested URL returned error: 503
HTTP/2 503 
content-type: application/json
docker-distribution-api-version: registry/2.0
date: Thu, 27 Apr 2023 09:23:52 GMT
content-length: 68
x-github-request-id: C570:A4DD:4ABE1F:4D43A7:644A3F21

curl: (22) The requested URL returned error: 503
HTTP/2 503 
content-type: application/json
docker-distribution-api-version: registry/2.0
date: Thu, 27 Apr 2023 09:24:01 GMT
content-length: 68
x-github-request-id: C570:A4DD:4AC384:4D48E2:644A3F28

curl: (22) The requested URL returned error: 503
HTTP/2 503 
content-type: application/json
docker-distribution-api-version: registry/2.0
date: Thu, 27 Apr 2023 09:24:11 GMT
content-length: 68
x-github-request-id: C570:A4DD:4ACA0A:4D4F38:644A3F31

...

`

**Comment by MikeMcQuaid** [comment]
https://www.githubstatus.com/incidents/vsc464zj7gv4
