### ISSUE TITLE
Skylight Instrumentation

### ISSUE THREAD

**Issue by chancancode** [Homebrew/formulae.brew.sh#88]
Hello!

I work at [Skylight](https://www.skylight.io/). We are launching a [program](https://www.skylight.io/oss) to offer free Skylight accounts to open source apps (similar to Github and Travis), so I am reaching out to see if this is something you would be interested in.

If you’re not already familiar with Skylight, it is a smart profiler for Rails apps. Skylight makes it easy to pinpoint performance issues in Rails applications.

We work on a lot of open source projects ourselves, and in our experience it can be pretty hard to get contributors to work on application performance issues. Few contributors consider working on performance problems, and the ones that might be interested may not even know where to start. By making performance information more accessible, we hope to inspire potential contributors to tackle slow parts of your app, and have a good way to see if their contributions helped.

For reference, this is the [Skylight dashboard](https://oss.skylight.io/app/applications/g0gJSNnzYAws/) we set up for [The Odin Project](https://www.theodinproject.com/). It should give you a pretty good idea of how Skylight works.

Integrating Skylight to a Rails application is very easy. All you have to do is add the gem to your Gemfile and set an environment variable with your authentication token. (We are happy to send a pull request.) If you’re interested in setting this up or if you have any questions, you can reach us here or at [support@skylight.io](mailto:support@skylight.io).

We'd also love to feature you on our [website](https://www.skylight.io/oss) as one of the first open source organizations using Skylight. We hope you’ll join us in helping to make performance an accessible way to contribute to an open source project!

**Comment by koraktor** [comment]
I used the free Skylight trial a few years ago (see ebfaf3bdf47a61a0de66566c946b7cc595aa910b).

The results helped a lot and I even fixed some performance issues back then. So I would be really happy to integrate it again.

@MikeMcQuaid Any thoughts on this?

**Comment by MikeMcQuaid** [comment]
@chancancode Please don't mass post this on open source projects.

@koraktor I'm happy to use it if it's useful to you.

**Comment by chancancode** [comment]
@MikeMcQuaid sorry about that.

Just to clarify, these are not mass posted though, at least not in the usual sense – it’s not automated and not in large volume.

I personally found and reached out to a handful (less than 10) open-source Rails apps and only resorted to issue trackers if there aren’t other contact information listed. (Presumably that’s the preferred communication channel.)

I can understand why you might feel otherwise, since I reached out to two of your projects, my appologies.

**Comment by chancancode** [comment]
@koraktor if you are interested, the easiest way would probably be for you to create an app/account on skylight.io (in trial mode, so no credit card required). Once you have done that we can flip the OSS flag on the app.

Alternatively, I can do that for you and submit a pull request. In that case you might want to send us an email at support@skylight.io so we can send you the API key.

**Comment by koraktor** [comment]
@chancancode I already have an account. I renamed the app to `formulae.brew.sh`.

**Comment by chancancode** [comment]
@koraktor Awesome. I'll set it up for you and message you the details off-thred.
