### ISSUE TITLE
Make aliases redirect in formulae.brew.sh

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/formulae.brew.sh#947]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

A number of formulae have aliases, which makes it easier to interact with them. For example, one can `brew install python` and under the hood Homebrew will translate `python` to `python@3.11`. This is a good user experience and users don’t need to worry about the intricacies of the exact formula name.

However, the same does not apply to https://formulae.brew.sh/. We can link to a specific formula (https://formulae.brew.sh/formula/python@3.11) but not its aliases (https://formulae.brew.sh/formula/python, https://formulae.brew.sh/formula/python3, https://formulae.brew.sh/formula/python@3).

Making aliases redirect to the formula they point to at any given time would allow users to more accurately peruse the website, even when one cannot easily confirm what an alias points to (e.g. when on mobile).

### What is the motivation for the feature?

Consistency with other homebrew commands and easier navigation of https://formulae.brew.sh/ without needing to resort to leaving the browser and using the command-line to `brew info` an alias for its true name (which is not possible on mobile).

The URL pattern is so predictable that typing what you want can help make sure you’re accessing the right formula. It also makes it possible to make tools which take advantage of that consistency, such as a Siri Shortcut.

### How will the feature be relevant to at least 90% of Homebrew users?

It’s unlikely that 90% of Homebrew users visit https://formulae.brew.sh/, but the feature would be relevant to those who do by making navigation more intuitive by mirroring the command-line names.

### What alternatives to the feature have been considered?

While the website search is decent, it can occasionally be confusing. By using the search bar on https://formulae.brew.sh/ and typing `python`, one sees:

```
app-engine-python (disabled)
boost-python3
python-build
python-gdbm@3.11
python-launcher
```

None of which is the one we want. Searching for `python@3` yields:

```
python@3.10
python@3.11
python@3.7 (disabled)
python@3.8
python@3.9
```

Better, but the top result isn’t the most current version and there’s no guarantee the most up-to-date version is even showing up.

Searching for `python3`:

```
boost-python3
Also known as: python, python3, python@3
Python 3 bindings for the Cairo graphics library https:/ …
Implementation of Python 3 in Python https://pypy …
Implementation of Python 3 in Python https://pypy …
```

Most aren’t formulae. The correct one is there, though again not as the top result and a user has no guarantee that’s what the alias is pointing to.

**Comment by SMillerDev** [comment]
If the goal is to improve search, I am pretty sure this won't help. I think the best way to improve the formula search is to start feeding it our own data, not having algolia crawl it (which does work well for docs and the main page).

**Comment by vitorgalvao** [comment]
> GitHub Pages only has the ability to do HTML redirects which are kinda gross for this sort of thing

Hadn’t considered that, as I hadn’t realised this was hosted on GitHub pages. I’d say an HTML redirect is still better than a 404, but I understand wanting to avoid those.

> I'm not sure this would make the search results any better and might make them worse

While the search itself could do with some tweaks, I see that as orthogonal. I debated even mentioning it in the `What alternatives to the feature have been considered?` section.

> feels like you'd only end up on those pages by URL hacking?

I don’t see that as a negative. One of the advantages of predictable URLs is that we can not only manually edit them but also create our own tools around it without needing to connect to and parse API responses.

> If the goal is to improve search

It’s not; search is unrelated (see above). The goal is to improve direct links.

---

I have poked around (even before creating the issue) but it wasn’t entirely clear how the pages are created. Looking again, it seems they might be generated from the individual JSONs which are created from another source, which would mean new JSONs would have to be created for each alias, which in turn could make search results worse by adding a lot of noise to them. Is that correct? If so, I agree it would not be worth it to pollute search in favour of this convenience. If I misunderstood and this would be feasible without touching search, I’d gladly take a look at the generation script if I’m pointed to it.

Also, thank you for moving the issue to the correct repo. I didn’t open it here initially because none of the templates was appropriate for a request and I thought you might prefer the thoroughness of the main repo.

**Comment by MikeMcQuaid** [comment]
> I think the best way to improve the formula search is to start feeding it our own data, not having algolia crawl it (which does work well for docs and the main page).

Yeh, we could pretty easily generate our own JSON when we generate other bits of JSON for formulae.brew.sh. @SMillerDev do you have docs for this handy?

> One of the advantages of predictable URLs is that we can not only manually edit them but also create our own tools around it without needing to connect to and parse API responses.
> The goal is to improve direct links.

What tools? Note: there are no direct links.

> which would mean new JSONs would have to be created for each alias, which in turn could make search results worse by adding a lot of noise to them. Is that correct?

Yes, probably.

> I’d gladly take a look at the generation script if I’m pointed to it.

Check out this for how things get built: https://github.com/Homebrew/formulae.brew.sh/blob/master/.github/workflows/scheduled.yml

**Comment by SMillerDev** [comment]
> Yeh, we could pretty easily generate our own JSON when we generate other bits of JSON for formulae.brew.sh.
> @SMillerDev do you have docs for this handy?

I don't, but it should be easy enough to find for Algolia. Probably a good idea to take analytics into account there too for the search ranking.

**Comment by vitorgalvao** [comment]
Improving the Algolia search is out of scope and unrelated to the initial request as it wouldn’t really make a difference when linking directly. It’s not something I’ll pursue, but neither is the original request since I agree that generating the extra JSON for every alias and polluting the search results isn’t optimal either. Thank you for considering.

I’m fine with closing this issue, or leaving it open if you want it to track the Algolia search improvements. Though it would probably make the most sense as a new issue.

**Comment by MikeMcQuaid** [comment]
Ok, thanks @vitorgalvao!
