### ISSUE TITLE
Index Brewsci/bio

### ISSUE THREAD

**Issue by sjackman** [Homebrew/formulae.brew.sh#95]
Is it possible to index Brewsci/bio and Brewsci/science?
https://github.com/Brewsci/homebrew-bio
https://github.com/Brewsci/homebrew-science

**Comment by MikeMcQuaid** [comment]
Personally I think this should only index official taps i.e. not davidchall/hep or Brewsci/*.

**Comment by MikeMcQuaid** [comment]
Also, diplomatically @sjackman, I don't think it's particularly responsible for you to be trying to boost the visibility of a tap that says in the README "This tap is not maintained.".

**Comment by koraktor** [comment]
@sjackman Are they? Homebrew/science is deprecated and shouldn’t be browseable.

**Comment by sjackman** [comment]
Yep. For example http://formulae.brew.sh/formula/gatk
