### ISSUE TITLE
utf8cpp 4.0.1 has no working imported CMake target

### ISSUE THREAD

**Issue by ufleisch** [Homebrew/formulae.brew.sh#973]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Build TagLib on Mac via GitHub Actions using `brew install utf8cpp`

## What happened (include screenshots)

Build no longer works, probably since version 4.0.1, `#include <utf8.h>` is not found.

## What you expected to happen

Build to succeed.

How to reproduce:
- Try to build https://github.com/taglib/taglib/commits/master [8c63c877], it will fail because utf8.h is not found.
- Try to build the following commit [70b4ce79], it will work because the following patch has been added:
```
diff --git a/taglib/CMakeLists.txt b/taglib/CMakeLists.txt
index 911ce058..89f527d1 100644
--- a/taglib/CMakeLists.txt
+++ b/taglib/CMakeLists.txt
@@ -343,6 +343,16 @@ add_library(tag ${tag_LIB_SRCS} ${tag_HDRS})
 target_link_libraries(tag $<$<TARGET_EXISTS:utf8::cpp>:utf8::cpp>)
 target_link_libraries(tag $<$<TARGET_EXISTS:ZLIB::ZLIB>:ZLIB::ZLIB>)
 
+# Homebrew utf8cpp 4.0.1 seems to have issues. utf8.h is not found because
+# imported target utf8::cpp does not exist. The imported target utf8cpp::utf8cpp
+# includes non-existent path /usr/local/include/utf8cpp and cannot be used.
+# Therefore the following (temporary) hack is used to find the utf8cpp includes.
+if(APPLE)
+  if(EXISTS /usr/local/include/utf8.h)
+    include_directories(/usr/local/include)
+  endif()
+endif()
+
 set_target_properties(tag PROPERTIES
   VERSION ${TAGLIB_SOVERSION_MAJOR}.${TAGLIB_SOVERSION_MINOR}.${TAGLIB_SOVERSION_PATCH}
   SOVERSION ${TAGLIB_SOVERSION_MAJOR}
```

The comment describes the problem: Target `utf8::cpp` does not seem to exist. The imported target `utf8cpp::utf8cpp` from _/usr/local/share/utf8cpp/cmake/utf8cppTargets.cmake_ contains a non existing include path _/usr/local/include/utf8cpp_ and the configure step therefore will fail. Could you please add an imported target `utf8::cpp` with correct include path?

**Comment by iMichka** [comment]
Hi. It looks like you opened two similar issues. Can we close this one and only keep https://github.com/Homebrew/homebrew-core/issues/153289?

**Comment by ufleisch** [comment]
Yes, sorry, I noticed only after opening this issue, that this tracker is probably only for formulae.brew.sh.
